### ISSUE TITLE
0.6.8 dll/so missing

### ISSUE THREAD

**Issue by Neustradamus** [gkdr/lurch#131]
@gkdr: Can you add missing dll/so?
-> https://github.com/gkdr/lurch/releases/tag/v0.6.8
Thanks in advance.

**Comment by wnereiz** [comment]
Excuse me, but which dll/so are missing? I find only the source code.

**Comment by Neustradamus** [comment]
@wnereiz: https://github.com/gkdr/lurch/releases/tag/v0.6.7 vs https://github.com/gkdr/lurch/releases/tag/v0.6.8

**Comment by gkdr** [comment]
Unfortunately I still don't have a way to compile the plugin for Windows myself, and frankly I forgot to ask @EionRobb, who is kind enough to usually do it. Could you help out again, please?

By the way, I'm currently trying to set up automated builds for carbons (see https://github.com/gkdr/carbons/issues/27) because the plugin is much smaller and has less dependencies. Unfortunately I know nothing about compiling stuff on Windows, so it could still take me a while.

**Comment by EionRobb** [comment]
[lurch-0.6.8.zip](https://github.com/gkdr/lurch/files/2912158/lurch-0.6.8.zip)
I haven't tested it, but I have compiled it :)

**Comment by Neustradamus** [comment]
Thanks @EionRobb!
@gkdr: Who compile the .so?
Good to add into https://github.com/gkdr/lurch/releases/tag/v0.6.8 no?

**Comment by Kudalufi** [comment]
The version currently available at https://eion.robbmob.com/lurch/ does not work with either Pidgin 2.12 or 2.13 for Windows.  The one available above does.  Can we get the official download location for the Windows version updated with the above?

**Comment by gkdr** [comment]
I intended to use this issue for setting up an automated build like I mentioned, but I'm currently working on something else (as you can see on the dev branch) and it might take a while and I'd rather just close this. 

I also forgot to add the .dll to the releases because I mixed up everything in my head. It is available on the releases page now too. @Neustradamus, I usually also just added the .so I compiled to the release, but I don't know if it's even useful since I'm not sure it even works on other computers, and think most people on Linux just compile it themselves.

@Kudalufi If you want to tell me what exactly is not working, please open a new issue.
