### ISSUE TITLE
Need a way to detect and recreate missing or corrupted axc_db.sqlite

### ISSUE THREAD

**Issue by persmule** [gkdr/lurch#134]
For example, If the axc_db.sqlite corresponded to one of my account is missing, lurch will try to access it as if it still existed (with an empty axc_db.sqlite file created), and I even lose access to all lurch command including "/lurch help"（with "[Failed to access axc db](#12 )" reported）. The only way to recover from this situation is to remove the corresponding "lurch_initialised" flag inside accounts.xml manually, thus triggering lurch to reinitialize axc_db.sqlite files.

**Comment by gkdr** [comment]
I'm currently rewriting the commands so that only those actually requiring the database access it. Afterwards, the `/lurch uninstall` command should at least set the flag to false, enabling someone to recover from this.

I will check the issue with an empty database being created though, thanks for pointing it out.

**Comment by Whovian9369** [comment]
Gonna mention that this is still an issue, due to that not being in the released binary, due to that (the Windows binary in this case) being from 2018-07-26. Would like to request a "Stable" update be released with this, as... It's QUITE an annoying issue.

**Comment by EionRobb** [comment]
@Whovian9369 want a new dll? :)

**Comment by Whovian9369** [comment]
Oh please, @EionRobb !

**Comment by EionRobb** [comment]
@Whovian9369 https://eion.robbmob.com/lurch/dev/lurch.dll

**Comment by Whovian9369** [comment]
Thank you!
