### ISSUE TITLE
Question: Scenario to hit 'AXC_ERR_INVALID_KEY_ID'?

### ISSUE THREAD

**Issue by geobra** [gkdr/lurch#156]
Hi

I am using libomemo together with axc in shmoose xmpp client [1]. I ported lurch and removed all the libpurple dependencies. All went fine so far. The only part in the integration tests during omemo messaging, which didn't get hit is:

lurch.c, line 1990:
 } else if (ret_val == AXC_ERR_INVALID_KEY_ID) {

and obviously lurch_pep_bundle_for_keytransport never gets called.

What is the Use-Case to hit the 'AXC_ERR_INVALID_KEY_ID' Scenario? I fo not have any idea how to trigger this.

Thank you for your great work of providing this projects!

[1] https://github.com/geobra/harbour-shmoose

**Comment by gkdr** [comment]
hello! thank you, i'm glad this project can be of help.

let me walk you through the code:
- the code you're referencing deals with message decryption. i'm sure you knew that from the function name :slightly_smiling_face: 
- now, there is no function in `libsignal-protocol-c` to check whether a message is a *pre key message*  or a regular message. a pre key message is only received if the other party has no session with you and took a pre key from your bundle to build one.
- OMEMO (at first) also did not have the `prekey` attribute (which is still missing from my code), so the code you're looking at always tries to use a message as a pre key message first. if it's not, it just tries to decrypt it regularly.
- the line you're asking about however only happens if it actually is a pre key message, but the pre key ID the other party used for establishing the session is invalid. a prekey is deleted after use, so this can happen if two contacts tried to establish a session at the same time and happened to pick the same pre key for it. usually, after a prekey is deleted a new one is generated and the bundle is republished.
- so in order to establish a session anyway, a key transport message is sent as fallback. iirc the omemo XEP business rules state to do that. however it means that the actual message body of the prekey message got lost.

hope i could clear things up a little.
(since you referenced the master branch i would also like to suggest you use the more up-to-date dev branch as a base for any code instead.)

**Comment by geobra** [comment]
Okay, got it. Thank you!
Just wondering how I would construct an automated test for this - but this is something I have to solve by myself ;-).

I was not aware of the dev branch. You did a lot of refactoring and split up of functionality there. That will also help me to minimize the ported code. I will stay on master in the first place. I will finish the integration and testing in the shmoose client first and then continue with switching to your dev branch.
