### ISSUE TITLE
Custom smileys are broken in OMEMO-enabled chat

### ISSUE THREAD

**Issue by Reepca** [gkdr/lurch#166]
To reproduce: send a custom smiley in an OMEMO-enabled chat (I tested in a one-to-one chat).

What I expect to happen: configured image shows up for recipient.

What happens: configured shortcut text shows up for recipient.

When I disable OMEMO with /lurch disable, and then send the custom smiley again, the configured image shows up as expected for the recipient.

**Comment by gkdr** [comment]
hi @Reepca, thanks for the report!
i checked it out and unfortunately it works as intended. this is what a message with a custom smiley looks like:
```xml
<message type='chat' id='purple16081625' to='a@localhost/qRUmNBTl'>
  <active xmlns='http://jabber.org/protocol/chatstates'/>
  <body>:test:</body>
  <html xmlns='http://jabber.org/protocol/xhtml-im'>
    <body xmlns='http://www.w3.org/1999/xhtml'>
      <p><img alt=':test:' src='cid:sha1+c35a9fc52bb556c79f8fa540df587a2bf465b940@bob.xmpp.org'/></p>
    </body>
  </html>
</message>
```

aside from a few exceptions (like that `<active>` element), all elements are stripped to prevent data leaks, since only the `<body>` can be encrypted. iirc, this is solved in the 'new' omemo, which encrypted the whole stanza and not just the body.
