### ISSUE TITLE
XML parser error for JabberStream 0343AFD0: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute

### ISSUE THREAD

**Issue by ghost** [gkdr/lurch#172]
I am sorry but I must report that for me omemo still not working.
When I enable it I get this failuere :

```
XML parser error for JabberStream 0343AFD0: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
```
And When I try to send a message I get 
```
(22:43:38) g_log: xmlnode_to_str_helper: assertion `node != NULL' failed
(22:43:38) g_log: jabber_send_raw: assertion `data != NULL' failed
(22:43:38) g_log: jabber_is_stanza: assertion `packet != NULL' failed
(22:43:38) jabber: XML parser error for JabberStream 03398850: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(22:43:38) lurch: lurch_bundle_create_session: failed to import xml into bundle (-12000)
(22:43:38) lurch: lurch_bundle_request_cb: failed to create a session (-12000)
```
I am on Windows 7 portable if you nheed more information please contact ask I will post it.

**Comment by EionRobb** [comment]
The "XML parser error" is normal, due to the compatibility with other clients requiring a malformed xml namespace.  The `xmlnode_to_str_helper: assertion `node != NULL' failed` is the error

**Comment by gkdr** [comment]
hi @ecxod, thanks for the report. sorry it's still not working for you. i suspect it's not windows but some other moving part - between clients and servers and omemo implementations there are unfortunately a lot.

as eion said, that "error" you pointed out is more like a warning, and it will appear on every message. the failed assertions are more of a problem. could you post the raw xml from the debug log? you can remove the jabber IDs, everything else is public anyway.

**Comment by ghost** [comment]
I did this already here : https://github.com/gkdr/lurch/issues/159#issue-791942979
I think you should enter with anydesk on my computer and check it out yourself. I am not able to give you the information more then I did. Or simple make a version that is more verbouse.  Then I can give more informations. 
Also the _**/lurch**_ commands are mostly undocumented.
We need a graphical UI where the fingerprints are shown and can be turned on and off etc.
Gajim and Conversations are positive examples. But we need this for Pidgin.

**Comment by gkdr** [comment]
you did do it over in the other issue, sorry for not coming back to you about it.
the issue here is slightly different though, as something seems to be `NULL`. i don't see the messages about failing assertions in the debug logs of the other issue. could you repeat that and show me the raw xml here too?

you are right, the debug log should contain more information. i'm tracking that here: https://github.com/gkdr/libomemo/issues/35

what information are you missing from `/lurch help`? a graphical interface would likely be easier to use and i laid the foundation for it by rewriting the functionality used by the commands as an API, which is e.g. used by the chatty client. if you know GTK, it should be straightforward :slightly_smiling_face: i'm sure there is an issue tracking this somewhere. i should update it.

**Comment by ghost** [comment]
The topic is obsolete, as the new  [offline version](https://sourceforge.net/projects/pidgin/files/Pidgin/2.14.6/pidgin-2.14.6-offline.exe) works perfect. Ok, relative perfect ;-)
