### ISSUE TITLE
Update build instructions for Debian stable in README

### ISSUE THREAD

**Issue by galaxor** [gkdr/lurch#35]
Hi.  I'm having some trouble building this.  It looks like maybe I'm not using the right version of libmxml?  
If there's a particular version required, could that be documented in the build scripts so it would nope out if you had a version that was too old?

I'm using version 2.6-2 from Debian Jessie.

Here's what happened when I tried to build it.
[buildlog.txt](https://github.com/gkdr/lurch/files/828700/buildlog.txt)

Here's the Dockerfile of the container I was building it in.
[Dockerfile.txt](https://github.com/gkdr/lurch/files/828703/Dockerfile.txt)

**Comment by gkdr** [comment]
Sorry, I forgot to add this information to the README after that was discussed in #30.
The version of libxml that comes with Debian Stable is quite old (iirc from 2009), and I use functions from the 2.7 release. You can find 2.10 in the Testing repositories.

Since I'm just using make and not autotools I'm not sure if there's a nice way to test for specific versions of libraries, but I agree that it would be nice to be informed of that, so maybe I can find something.

**Comment by galaxor** [comment]
Great, thanks.  Here's a docker config that built lurch for me no problem.

```
FROM debian:testing

RUN apt-get update
RUN apt-get install -y build-essential cmake libgcrypt20-dev libpurple-dev libxml2-dev libsqlite3-dev libglib2.0-dev libmxml-dev 
RUN apt-get install -y git
```

**Comment by gkdr** [comment]
Glad it worked. I'll reopen this issue so I won't forget to update the README this time...
