### ISSUE TITLE
lurch 0.6.4 Error: undefined symbol: key_exchange_message_deserialize

### ISSUE THREAD

**Issue by mmirg** [gkdr/lurch#42]
I just updated lurch from 0.6.2 to 0.6.4 (and carbons from 0.1.2 to 0.1.3) and am getting the following error when trying to enable lurch in pidgin on Linux:

```
Error: undefined symbol: key_exchange_message_deserialize
Check the plugin website for an update.
```

**Comment by gkdr** [comment]
That is very weird.
The function this concerns was deleted in libsignal, and I deleted the code that goes with it, except that I forgot to update/delete the test cases (which is the only place this function is used now).

I can only think of something to do with the submodules, but you must have updated them, or the old _axc_ would still be there (I did not use that code anywhere either way).

But just to make sure, what is the output of `git submodule status --recursive`?  Mine looks like the following:
``` 
032fba9c5610d33298cccaf400af9a8813b03f2f lib/axc (v0.3.0)
e59089a644ca747ed50442eb8804266618f11c0b lib/axc/lib/libsignal-protocol-c (v2.3.0-8-ge59089a)
00b5f90a996c18f87a887a9602173921244c9f40 lib/libomemo (v0.5.0)
```
So if yours doesn't, maybe try `git submodule update --init --recursive` (the last argument is new and important). Otherwise I'll try to come up with something else.

**Comment by mmirg** [comment]
I get the same output for `git submodule status --recursive`:

```
 032fba9c5610d33298cccaf400af9a8813b03f2f lib/axc (v0.3.0)
 e59089a644ca747ed50442eb8804266618f11c0b lib/axc/lib/libsignal-protocol-c (v2.3.0-8-ge59089a)
 00b5f90a996c18f87a887a9602173921244c9f40 lib/libomemo (v0.5.0)
```

**Comment by gkdr** [comment]
Okay, I cannot imagine why then, because I do not use that function anywhere in the code, only in the test cases which should not be part of the final .so.

Did you try `make clean-all`?

**Comment by mmirg** [comment]
That did the trick, I had done` make clean` instead of `make clean-all` and had cruft left over from an older build.  My apologies for the trivial issue.

**Comment by gkdr** [comment]
No worries, glad it could be resolved this easily.
