### ISSUE TITLE
plain text inside span tags

### ISSUE THREAD

**Issue by sfdne** [gkdr/lurch#43]
if you change text size in pidgin, you could see the hole message as plaintext inside span tags in xmpp-console. i just saw this when i checked if lurch is running. i'm not a coder, so may be that's normal if so pls calm me.

**Comment by gkdr** [comment]
Can you tell me how you changed the text size?
And are you sure it is the XMPP console, not the debug console?

What this plugin does is take the contents of the `<body>` and encrypt them. If for some reason Pidgin puts text outside the message body, there might actually be a problem.

**Comment by sfdne** [comment]
i changed it in the chat window. and it doesn't matter which text attribute you change, it's allways the same behaviour. i.e color, size, font or something else.

**Comment by gkdr** [comment]
Oh, you can even change it from the message window, didn't even realize that
.
Well, Pidgin uses XHTML if you do any change at all, which in fact puts a whole copy of the message in a separate tag, as can be seen in the example on the XEP I linked:
```XML
<message>
  <body>hi!</body>
  <html xmlns='http://jabber.org/protocol/xhtml-im'>
    <body xmlns='http://www.w3.org/1999/xhtml'>
      <p style='font-weight:bold'>hi!</p>
    </body>
  </html>
</message>
```
Here, the `<body>` will get encrypted, but anything else will be left alone, including the `<html>`, as OMEMO does not define encryption of anything but the `<body>`.

I'll fix it tonight (by stripping it), until then you might want to reset the text settings (which I unfortunately assumed to be client-side).
Not sure where to put this yet, though, since this is purely a client-side thing. I guess it is better to add this to the OMEMO library as a security measure.

Thanks for bringing it up.

**Comment by gkdr** [comment]
@sfdne It's fixed, thanks for the discovery.
