### ISSUE TITLE
"error encrypting the message"

### ISSUE THREAD

**Issue by radasbona** [gkdr/lurch#53]
Hi,
I can' send encrypted messages from Pidgin. My system is Linux Mint 17, the receiver has conversations on his mobile. Conversations to conversations works well.

Here are all Debug Errors i get: 
(12:57:43) jabber: XML parser error for JabberStream 0x7fe59bf48ca0: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute

(12:57:43) lurch: lurch_bundle_create_session: failed to create a session from a bundle (-1002)
(12:57:43) lurch: lurch_bundle_request_cb: failed to create a session (-1002)

**Comment by gkdr** [comment]
Hi!

This seems to be the same issue as in #23, which is still unresolved (and I had other people report it to me on IRC as well).
As you can see in that issue, `-1002` is an error code from deep within `libsignal-protocol-c`.
By now I have updated it to a recent version, so the information in there that it might be a legacy issue is not current, but it might still be the case that the signature verification fails somehow. 
The other option is that for some reason NULL is passed to the function, I can't imagine why it works most of the time then though.

This could maybe be resolved if your friend messages you first, as this establishes a session.
If you want to help me debug it, you could run Pidgin through `gdb` and tell me if there's actually any NULL values.
In case you want to do that and need more instructions, I can try to provide a step-by-step guide.

**Comment by radasbona** [comment]
> This could maybe be resolved if your friend messages you first, as this establishes a session. <
Yes, it does. Strange.

Sure i want to help. Simply starting piding and trying to start a chat gives me this:

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pidgin...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

But im not familiar with this, a step-by step guide would be nice.

**Comment by gkdr** [comment]
Okay, sorry, I guess I was not clear enough - now that you have a session this won't work :D
So if you're willing to risk it again you'll have to go to  `~/.purple/`, open the `<jid>_axc_db.sqlite` file with `sqlite3`, and manually delete the session by typing `delete from session_store where name is 'your@friends.jid';`
If it still does not work then - i.e. you can reproduce the error - I'll make a gdb guide. Because it might just work for you now...

**Comment by radasbona** [comment]
No Problem,
i deleted the session in the database as you wrote. the error is back again.

**Comment by gkdr** [comment]
Sorry for the wait - but I think I have an even better idea now. I need you to tell me your friend's bundle (I don't need the JID, and all the other info in there is public anyway) and I will see if I can reproduce this myself, and you can just chat with your friend using the session he built by messaging you.

You can either try to message your OMEMO-using friend while there is no session and copy the incoming bundle which will look something like in [example 3 of the OMEMO specification](https://xmpp.org/extensions/xep-0384.html), just so that you know what you're looking for.

The other option is to do it manually.
For this, activate the _XMPP Console_ plugin that comes with Pidgin under _Tools -> Plugins_, after which you can find it at _Tools -> XMPP Console_.
Then, send the following request (but replace the JID and device ID):
```XML
<iq to='your@friends.jid' type='get'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.bundles:12345'/></pubsub></iq>
```

**Comment by radasbona** [comment]
I did it via Console. Here is the result:

<iq type='error' from='**MY CONTACTS J-ID**'>
	<pubsub xmlns='http://jabber.org/protocol/pubsub'>
		<items node='eu.siacs.conversations.axolotl.bundles:12345'/>
	</pubsub>
	<error code='400' type='modify'>
		<bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
		<text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Missing attribute 'id' in tag <iq/> qualified by namespace 'jabber:client'</text>
	</error>
</iq>

Is this you’re looking for?

**Comment by gkdr** [comment]
No, your server must be less lenient with errors than my local one, sorry (I use Prosody).
Just add a random ID:
```XML
<iq to='your@friends.jid' id='id123' type='get'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.bundles:12345'/></pubsub></iq>
```

**Comment by radasbona** [comment]
I'm use jabber.at, ejabberd afaik. 
Next try: 
[Error.txt](https://github.com/gkdr/lurch/files/981882/Error.txt)

Bedtime for me. 
If it still not what you looking for you can contact me via xmpp. (also in german)

**Comment by gkdr** [comment]
That looks exactly like what I need, thanks!
I'll see if I can reproduce it.

**Comment by gkdr** [comment]
I was in fact able to reproduce it and determined that it's not me passing NULL values, but the actual signature verification fails.
Before I open an issue upstream, can you do me a favour and ask your friend if other people were able to successfully contact him or her using other OMEMO clients?

**Comment by gkdr** [comment]
Okay, after [opening an issue over at libsignal-protocol-c](https://github.com/WhisperSystems/libsignal-protocol-c/issues/70), I was told that it should not have worked on Conversations because the Java library fails to verify the signature as well.

I'm not sure what the deal is here - IIRC it was always Conversations when this happens, so either it sometimes corrupts the bundle between generation and publication (ChatSecure had a similar issue), or maybe the server software corrupts the PEP node in a way that is still passes deserialization and it's only happening on Conversations because that is the most used OMEMO client.

The best thing I can do right now is to display a better error message giving the same hint I gave you - just try it the other way round and it will probably work.
I'll definitely tell it to the Conversations devs though.

**Comment by radasbona** [comment]
> Actually, do you know if it's possible to delete sessions on Conversations, and would you be willing to try?

I guess not, simply closing and reopen a chat doesn't create a new sessions. So conversations must be reinstalled (afaik, maybe wrong).

> I'll assume you just didn't notice it because Conversations doesn't shout at you in big red letters when that happens.

You mean our chats were unencrypted? 

> The best thing I can do right now is to display a better error message giving the same hint I gave you - just try it the other way round and it will probably work.

Sure, thanks for your help. And btw. Thanks for your Work an this plugin. :-)

**Comment by gkdr** [comment]
>I guess not, simply closing and reopen a chat doesn't create a new sessions. So conversations must be reinstalled (afaik, maybe wrong).

I guess you're right, so it's too much of a hassle.

>You mean our chats were unencrypted?

Yes and no, I mean that your friend just wrote to you instead (like I suggested to you) and the session was established from your bundle. I think you might have been put off from just continuing to talk by the very visible warning my plugin displays.

>Thanks for your Work an this plugin. :-)

You're very welcome!

**Comment by gkdr** [comment]
The related issue at `libsignal-protocol-c` was closed for age and inactivity, so I'll close this one too.
