### ISSUE TITLE
lurch can't access axc db

### ISSUE THREAD

**Issue by chaoscommander** [gkdr/lurch#7]
After successfully building and installing (thanks for the new build setup, much easier!) and setting LD_LIBRARY_PATH env variable so Pidgin would find libaxolotl-c.so (probably Gentoo specific), I could enable the plugin in Pidgin. Problem: it caused me to be unable to send any messages to anyone, always reporting that encryption had failed (even with people currently not using any kind of Axolotl-capable messenger). Here's pidgin's console output regarding that:

`(19:02:10) lurch: lurch_message_encrypt_im: failed to look up person1@domain.org in DB /home/user/.purple/user@domain.org/Hostname_omemo_db.sqlite (-14)
(19:02:10) g_log: xmlnode_to_str_helper: assertion 'node != NULL' failed
(19:02:10) g_log: jabber_send_raw: assertion 'data != NULL' failed`

Typing any command like `/lurch help` results in the message "Failed to access axc db." in the conversation window.
(sqlite is installed)

**Comment by gkdr** [comment]
I thought it is a good default to never send unencrypted messages if you expect them to be encrypted. In this case, the plugin cannot look up if it is to be encrypted or not, so it does not send the messages. I still think this is valid since the plugin just doesn't work right now and you have to deactivate it anyway.

The DB functions generally return the negated SQLite error codes - "14" is SQLITE_CANTOPEN.
I get the the path of the database by calling purple_user_dir() (which should be ~/.purple), then get what libpurple returns as the own account name and add _omemo_db.sqlite. Now for me this was always the bare JID (user@domain.org) with a trailing "/", so I just cut that off. It seems that your account name includes the hostname somehow, so that doesn't work (if you look closely, the last letter of the hostname should be missing). So now it is looking for a directory user@domain.org, which does not exist.

Since the DB is needed for most commands, I access it at the beginning of the command handling, which is why even the help doesn't work. Maybe I should fix that...

Anyway, your problem should be fixed in c4869dc, if not I'm sure we can figure it out. Thanks for helping me make it work for everyone!

**Comment by chaoscommander** [comment]
Yep, works for me now! :) Helping you is much more fun than with other open source projects I reported bugs to so far. I'm impressed with how fast you fix things - other project devs don't even react for months (and then they say "works for me, closed"). ;)
