### ISSUE TITLE
Broken when used in combination with OTR

### ISSUE THREAD

**Issue by mejo-** [gkdr/lurch#75]
When using both `lurch` and the OTR plugin, I get the following error for non-OMEMO contacts:

```
(19:31:53) lurch: lurch_message_encrypt_im: failed to get device id (-21)
(19:31:53) g_log: xmlnode_to_str_helper: assertion 'node != NULL' failed
(19:31:53) g_log: jabber_send_raw: assertion 'data != NULL' failed
```

Any idea why this is happening?

**Comment by gkdr** [comment]
Do you mean both plugins are active at the same time, or are you trying to use both OTR and OMEMO for some user?

**Comment by gkdr** [comment]
Sorry, I never tested this. I'll try having a look but I'm a bit short on time currently.

**Comment by mejo-** [comment]
I'm closing this bugreport as I didn't discover the issue again. I started over with a fresh installation of lurch a few weeks ago and use it together with OTR since then. Communication with OMEMO contacts works fine, even though the OTR plugin is still enabled.

I have to admit though, that I disabled OTR on a per-contact basis for OMEMO capable contacts (to prevent OTR foo with them).

**Comment by vn971** [comment]
@mejo- Can we maybe show a warning when trying to communicate with OTR-forced buddies? :thinking: 
![2020 03 13_18:45:41](https://user-images.githubusercontent.com/1547617/76646245-ee6ffc80-655a-11ea-8b5d-9dbd81fbf208.png)
The problem is totally reproducible with latest OTR (4.0.2 from ArchLinux) and Lurch (v0.6.8.r0.g3f74880).
